/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.7-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package edu.kit.datamanager.collection.web;

import edu.kit.datamanager.collection.domain.ServiceFeatures;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-07-09T15:21:24.632+02:00")
public interface FeaturesApi{

  @Schema(title = "Gets the service-level features.", name = "featuresGet", description = "This request returns the service-level features. Examples of service-level features might include whether or not the service supports assignment of PIDs for collection members, whether it supports pagination and cursors, whether it enforces  access controls, etc.", implementation = ServiceFeatures.class)
  @ApiResponses(value = {
    @ApiResponse(responseCode = "200", description = "Service Level Features")})
  @RequestMapping(value = "/features",
          produces = {"application/json"},
          method = RequestMethod.GET)
  ResponseEntity<ServiceFeatures> featuresGet();

}
